parameters:
  arduino.dir-placeholder:  '%%ARDUINO_DIR%%'               # escaped %ARDUINO_DIR%
  arduino.config-file:      '/project/arduino-cli.yaml'

  fs-helper.dir-mode: 0777
  fs-helper.work-dir: '/tmp/arduino-cli'
  fs-helper.acli-src: '/project/build-tools/src'

services:
  command-arduino-cli-deploy:
    class: Thermo\Commands\DeployArduinoCliCommand
    arguments:
      - '@helper-filesystem'
      - '@helper-github'

  command-arduino-cli-config:
    class: Thermo\Commands\GenerateConfigYaml
    arguments:
      - '%arduino.dir-placeholder%'
      - '%arduino.config-file%'

  cli-app:
    class: Symfony\Component\Console\Application
    calls:
      - [ add, [ '@command-arduino-cli-deploy' ] ]
      - [ add, [ '@command-arduino-cli-config' ] ]

  helper-filesystem:
    class: Thermo\Helpers\FileSystemHelper
    arguments:
      - '%fs-helper.dir-mode%'
      - '%fs-helper.work-dir%'
      - '%fs-helper.acli-src%'

  helper-github:
    class: Thermo\Helpers\GithubHelper

